### ISSUE TITLE
[RFE] fio package installation on client instances upon instance creation

### ISSUE THREAD

**Issue by VasishtaShastry** [red-hat-storage/cephci#1529]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.

We need fio package to be installed on client node for covering rbd and cephfs scenarios.
Would be nice to install the package on client nodes during prerequisites.

**Describe the solution you'd like**
Install `fio` package during the installation of package on client nodes during install pre-requisites.

**Comment by psathyan** [comment]
One can install any package on the client node. This feature exists.

```
  - test:
      abort-on-fail: true
      config:
        command: add
        id: client.1
        node: node6
        install_packages:
          - ceph-common
          - fio   # <== add any yum available tools/utils/packages
        copy_admin_keyring: true
      desc: Configure the RGW client system
      destroy-cluster: false
      module: test_client.py
      name: configure client
```
Would you be able to revert any changes made to `utils.py`
