### ISSUE TITLE
allow configurable grafana container image with cephadm

### ISSUE THREAD

**Issue by ktdreyer** [red-hat-storage/cephci#431]
For `ceph-ansible`, we could configure the grafana container image location during the tests.

For `cephadm`, I don't think cephci supports this yet. It looks like it just uses the default container image that is hardcoded as `DEFAULT_GRAFANA_IMAGE` into `/usr/sbin/cephadm`.

This causes problems in the following scenarios:

1. We will want to test un-released versions of the grafana dashboard image.
2. We will hard-code the beta refspec, `registry.redhat.io/rhceph-beta/rhceph-5-dashboard-rhel8:latest` in our internal builds before we ship to that location. cephci will fail to deploy grafana until we ship there.
3. We will hard-code the GA refspec, `registry.redhat.io/rhceph/rhceph-5-dashboard-rhel8:latest` in our internal builds before we ship to that location. Again cephci will fail to deploy grafana until we ship there.

**Comment by psathyan** [comment]
I believe it is possible to configure a custom image for **prometheus, node-exporter, grafana** and **alert-manager**. One would need to insert a `config` section in the test that deploys the service.

For example
in bootstrap
```
tests:
...
  - test:
      name: Bootstrap the cluster
       config:
          verify_cluster_health: true
          steps:
...
             - config:
                  command: shell
                  args:
                     - "ceph config set mgr mgr/cephadm/container_image_grafana registry.redhat.io/rhceph-beta/rhceph-5-dashboard-rhel8:latest"
              - config:
                   command: apply
                    service: grafana
                    args:
                       placement:
                         label: grafana 
```
as a test step
```
- test:
    name: custom grafana image
    desc: Configure the custom image via cephadm for grafana
    module: test_boostrap.py
    config:
      command: shell
      args:
         - "ceph config set mgr mgr/cephadm/container_image_grafana registry.redhat.io/rhceph-beta/rhceph-5-dashboard-rhel8:latest"
- test:
    name: deploy grafana
    desc: apply grafana service on nodes with role grafana
    module: test_monitoring.py
    config:
      command: apply
      service: grafana
      args:
        placement:
          label: grafana
```
However, we don't have any tests exercising the custom image option at the moment. 

As a first step, we could create a separate suite that exercises custom image instead of extending `cephadm.yaml` test suite available at `suites/pacific/cephadm/` folder.
