### ISSUE TITLE
provide a way to upgrade to custom versions of ceph with upgrade test

### ISSUE THREAD

**Issue by pdhiran** [red-hat-storage/cephci#4499]
**Is your feature request related to a problem? Please describe.**
We can currently bootstrap a cluster with specified version of ceph, but then later, we do not have a option to pick a intermediate ceph version for upgrade. The upgrade test by default upgrades to latest version for which the run is triggered.

Enhancement request for the upgrade test, where we can specify a particular version for upgrade, just like installation.

**Describe the solution you'd like**
eg :  Start install of cluster with 6.1 builds. Note that the run is triggered for 8.1 builds.

```
  - test:
      name: cluster deployment
      desc: Execute the cluster deployment workflow.
      module: test_cephadm.py
      polarion-id:
      config:
        verify_cluster_health: true
        steps:
          - config:
              command: bootstrap
              service: cephadm
              base_cmd_args:
                verbose: true
              args:
                rhcs-version: 6.1
                release: z1    
                mon-ip: node1
```

then in the suite, we have upgrade test, which by default, upgrades to latest, in this case, nightly 8.1. we want a way to specify custom version here.

eg : 

```

  - test:
      name: Upgrade cluster to specified ceph version
      desc: Upgrade cluster to latest version
      module: test_cephadm_upgrade.py
      polarion-id: CEPH-83573791
      config:
        command: start
        service: upgrade
        base_cmd_args:
          verbose: true
          rhcs-version: 7.1
          release: z1    
        verify_cluster_health: true
      destroy-cluster: false
      abort-on-fail: true

```

and then at the end, trigger the upgrade again to the latest

```

  - test:
      name: Upgrade cluster to latest 8.x ceph version
      desc: Upgrade cluster to latest version
      module: test_cephadm_upgrade.py
      polarion-id: CEPH-83573791
      config:
        command: start
        service: upgrade
        base_cmd_args:
          verbose: true 
        verify_cluster_health: true
      destroy-cluster: false
      abort-on-fail: true

```

**Describe alternatives you've considered**

**Additional context**
This types of upgrade paths required for verification of customer issues and fixed
